# conda env create -f environment.yml
# conda activate fem

name: fem
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.21
  - scipy>=1.8
  - matplotlib>=3.5
  - pyamg>=4.2
  - pip
  - pip:
      - mat73
